plugins:
  sms_verification_enabled:
    default: false
    client: false

  twilio_account_sid:
    default: ""
    client: false

  twilio_auth_token:
    default: ""
    client: false

  twilio_from_number:
    default: ""
    client: false
