sms_verification_enabled:
  default: false
  client: true

sms_gateway_provider:
  default: "twilio"

sms_gateway_account:
  default: ""

sms_gateway_token:
  default: ""
  secret: true

sms_gateway_sender:
  default: ""
